### ISSUE TITLE
Add Previous Button

### ISSUE THREAD

**Issue by DanielOnzo** [TrenzaloreStrax/market-tool#17]
![4d1667bbd7a1725daa1f9da715ab7869](https://user-images.githubusercontent.com/90472530/132893709-3f63cf28-8df1-4d5b-ba11-3dd047d1790b.png)
On the item screen where it shows Active Orders, Recent Purchases, Recent Sales, and the graphs... there is a Next button. Would be helpful to have a Previous button as well

**Comment by TrenzaloreStrax** [comment]
Available in 1.4

![image](https://user-images.githubusercontent.com/74151174/133463334-3ac90f65-4916-4267-ab3f-a130b951cdac.png)
